/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        brand: {
          ink: 'var(--color-ink)',
          paper: 'var(--color-paper)',
          surface: 'var(--color-surface)',
          mist: 'var(--color-mist)',
          rose: 'var(--color-rose)',
          'rose-soft': 'var(--color-rose-soft)',
          'rose-deep': 'var(--color-rose-deep)',
          mauve: 'var(--color-mauve)',
          lilac: 'var(--color-mauve)',
          indigo: 'var(--color-rose-deep)',
          bloom: 'var(--color-bloom)',
          'bloom-deep': 'var(--color-bloom-deep)',
        },
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
      },
      fontFamily: {
        sans: ['var(--font-onest)', 'Inter', 'DM Sans', 'system-ui', 'sans-serif'],
        brand: ['var(--font-onest)', 'Inter', 'DM Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        9: ['var(--text-9)', { lineHeight: '1.2', letterSpacing: '-0.015em' }],
        10: ['var(--text-10)', { lineHeight: '1.2', letterSpacing: '-0.016em' }],
        11: ['var(--text-11)', { lineHeight: '1.2', letterSpacing: '-0.017em' }],
        12: ['var(--text-12)', { lineHeight: '1.3', letterSpacing: '-0.018em' }],
        14: ['var(--text-14)', { lineHeight: 'var(--lh-sm)', letterSpacing: 'var(--tracking-14)' }],
        16: ['var(--text-16)', { lineHeight: 'var(--lh-body)', letterSpacing: 'var(--tracking-16)' }],
        18: ['var(--text-18)', { lineHeight: '1.3', letterSpacing: '-0.021em' }],
        20: ['var(--text-20)', { lineHeight: 'var(--lh-lead)', letterSpacing: 'var(--tracking-20)' }],
        23: ['var(--text-23)', { lineHeight: 'var(--lh-title-sm)', letterSpacing: 'var(--tracking-23)' }],
        26: ['var(--text-26)', { lineHeight: '1.2', letterSpacing: '-0.026em' }],
        29: ['var(--text-29)', { lineHeight: '1.2', letterSpacing: '-0.027em' }],
        32: ['var(--text-32)', { lineHeight: 'var(--lh-title)', letterSpacing: 'var(--tracking-32)' }],
        36: ['var(--text-36)', { lineHeight: '1.1', letterSpacing: '-0.032em' }],
        48: ['var(--text-48)', { lineHeight: 'var(--lh-display-md)', letterSpacing: 'var(--tracking-48)' }],
        86: ['var(--text-86)', { lineHeight: '1', letterSpacing: 'var(--tracking-86)' }],
        152: ['var(--text-152)', { lineHeight: 'var(--lh-display)', letterSpacing: 'var(--tracking-152)' }],
      },
      fontWeight: {
        whisper: '200',
        thin: '300',
        body: '400',
        ui: '500',
        emphasis: '600',
        strong: '800',
      },
      maxWidth: {
        site: 'var(--max-width)',
        'screen-xl': 'var(--max-width)',
      },
      spacing: {
        element: 'var(--space-element)',
        card: 'var(--space-card)',
        section: 'var(--space-section)',
      },
      borderRadius: {
        lg: 'var(--radius-card)',
        md: 'var(--radius-card)',
        sm: 'calc(var(--radius-card) - 2px)',
        card: 'var(--radius-card)',
        image: 'var(--radius-image)',
        tag: 'var(--radius-tag)',
        input: 'var(--radius-input)',
        button: 'var(--radius-button)',
        pill: 'var(--radius-button)',
      },
    },
  },
  plugins: [],
}
